config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
  	member do
  		put "like", to: "pins#upvote"
  	end
  end

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	acts_as_votable
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Successfully created new pin"
		else
			render 'new'
		end
	end

	def show
		
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Successfully updated"
		else
			render 'edit'				
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def edit
		
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Pin Board
	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Pin Board", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Pin", new_pin_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Logout", destroy_user_session_path, method: :delete

			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign up", new_user_registration_path
					%li= link_to "Sign in", new_user_session_path
	
	.container
	- flash.each do |name, msg|
		= content_tag :div, msg, class: "alert alert-info"
	
	= yield

app/views/pins/_form.html.haml
= simple_form_for @pin, hmtl: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
			= pluralize(@pin.errors.count, "error")
			prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg
	
	.form-group
		= f.input :image, input_hmtl: { class: 'form-control' }

	.form-group
		= f.input :title, input_hmtl: { class: 'form-control' }

	.form-group
		= f.input :description, input_hmtl: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3.text-justify
	.row
		.panel.panel-default
			.panel-heading
				%h1 edit pin
			.panel-body
				%strong.center Current Image
				%br/
				= image_tag @pin.image.url(:medium)
				%br/
				= render 'form'
				= link_to "Cancel", pin_path

app/views/pins/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url), pin
			.panel-body
				%h2= link_to pin.title, pin
				%p.user
				Submitted by
				= pin.user#.email

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url(:medium)
			.panel-body.text-justify
				%h1= @pin.title
				%p= @pin.description
			.panel-footer
				.row
					.col-md-6
						%p.user
						Submitted by
						= @pin.user.email
					.col-md-6
						.btn-group.pull-right
							= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
								= @pin.get_upvotes.size
							- if user_signed_in?
								= link_to "edit", edit_pin_path, class: "btn btn-default"
								= link_to "delete", pin_path, method: :delete, data: { confirm: "Are you sure" }, class: "btn btn-default"